family_node.go, family_node_test.go, individual_node.go, individual_node_test.go, individual_nodes.go, individual_nodes_test.go
This has some breaking changes to the API to allow different documents to be used when comparing individuals. However, the functionality remains the same.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/61)
=> Added IndividualNodes.Compare() and IndividualComparison. Fixes #52

README.md, decoder.go, document.go, document_test.go, encoder.go, encoder_test.go, node.go, node_diff.go, node_diff_test.go, simple_node.go, simple_node_test.go
- Added CompareNodes() to recrsively compare nodes and return a nested NodeDiff. The NodeDiff comes with a string renderer.
- Improved the decoder to return an error and line number if a line cannot be parsed.
- Added NewDocumentFromString() to make it easier to handle strings containing GEDCOM data.
- Added GedcomLine() as the canonical way to render and compare node values. The encoder has been changed to use this as well.
- Added Node.Equals() to compare nodes by value.
- Added IsNil() as a safer alternative for testing if a Node interface is nil.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/69)
=> Added CompareNodes. Fixes #65

README.md, decoder.go, decoder_test.go, filter.go, filter_test.go, node.go, node_diff.go, node_test.go, simple_node.go, simple_node_test.go, util.go, util_test.go
- Filter() returns a new nest node structure by recursively filtering all children based on a callback FilterFunction.
- Added three built in filters; WhitelistTagFilter, BlacklistTagFilter and OfficialTagFilter.
- Added NewNode() to create a node of a specific type. It is better to use this than NewSimpleNode().
- Added NodeCondition() to make inline if statements with nodes easier. This was previously part of the private API.
- Added NodeGedcom() to make it easier to render complex nodes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/75)
=> Added Filter(). Fixes #73

birth_node.go, birth_node_test.go, decoder.go, decoder_test.go, document.go, document_test.go, encoder_test.go, filter_test.go, individual_node.go, individual_node_test.go, node_diff.go, node_diff_test.go, node_test.go, residence_node.go, residence_node_test.go, simple_node_test.go, tag.go, tag_test.go, util.go
- Greatly improved CompareNodes to use Equals instead of the previous node flattening technique that wasn't able to handle many scenarios. This required a lot of thought into how Equals works and is implemented for some nodes that already exist, but that also need to be created.
- Added BirthNode for BIRT tag.
- Added ResidenceNode for RESI tag.
- Added NewDocument() to easily create an empty document.
- Fixed a bug in Compound() where slices of non-Node caused a panic.
- Refactored the way options can be set on tags internally. This will make it a lot easier in the future to add more binary attributes to Tag constants.
- Changed Tag.Known to Tag.IsKnown which is more consistenly named with other boolean functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> Greatly improved CompareNodes. Fixes #76

node_diff.go, node_diff_test.go
IsDeepEqual returns true if the current NodeDiff and all of its children have been assigned to the left and right.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/88)
=> Added NodeDiff.IsDeepEqual. Fixes #86

filter.go, filter_test.go, name_node.go, name_node_test.go
- SimpleNameFilter() flattens NAME nodes.
- Added GedcomName() to return the simplified GEDCOM name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/95)
=> Add SimpleNameFilter(). Fixes #81

date_node.go, gedcom2html/main.go, gedcom2json/main.go, gedcom2text/main.go, gedcomdiff/diff_row.go, gedcomdiff/main.go, html/page.go, util/filter_flags.go
- Events are now removed if they do not have children.
- Added "-no-censuses" option.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/108)
=> gedcomdiff shows diff siblings. Fixes #106

gedcomdiff/diff_page.go, gedcomdiff/individual_compare.go, gedcomdiff/main.go
- The "-subset" option allows a lerger tree to be compared to a smaller tree by excluding individuals that only exist on the left side.
- Hide individuals that are the same in the gedcomdiff index.
- Show the birth/death dates of individuals for their headings in case all of that vital information does not show below.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/109)
=> Added "-subset". Fixes #105

gedcom2html/main.go
When exporting a large tree (1600 people) it will error with too many files open.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/111)
=> Close file handles in gedcom2html. Fixes #110

gedcom2html/places.go
In gedcom2html extra commas could appear before or after the place name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/112)
=> Remove extra "," from place names. Fixes #21

gedcom2html/event_statistics.go, gedcom2html/individual_events.go, gedcom2html/individual_in_list.go, gedcom2html/statistics_page.go, html/individual_dates.go, html/util.go, individual_node.go, individual_node_test.go, simple_node.go, util.go, util_test.go
- gedcom2html statistics page now shows all event types.
- A minor layout change for the statistic boxes so they fit better into two columns.
- Added IndividualNode.AllEvents() as an easier way to extract all nodes from an individual that have a Tag.IsEvent() of true.
- SimpleNode.String (and by extension most Node.String) now return the Value() rather than the GEDCOM rendered line which is much more approproate as a printing value.
- First() and Last() now accepts a much more flexible interface{} so it can be used with slices of more specific types.
- Added Dates() and Places() which return the shallow DateNodes or PlaceNodes respectively for each of the provided node arguments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Show all event types on statistics page. Fixes #20 and #91

gedcom2html/individual_list_page.go, name_node.go, name_node_test.go
- Individuals are now sorted (and hence indexed) by their surname rather than given name.
- Added NameFormat constants for NameName.Format, including the new NameFormatIndex.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/125)
=> Individuals sorted by surname. Fixes #121

decoder_test.go, html/page.go, sex_test.go
- The GEDCOM data was being read correctly by the browser needed to be told that all pages are UTF-8.
- I have also added some tests for Sex.String().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/130)
=> Set UTF-8 charset for HTML. Fixes #126

decoder.go, decoder_test.go, format_node.go, format_node_test.go, latitude_node.go, latitude_node_test.go, longitude_node.go, longitude_node_test.go, map_node.go, map_node_test.go, nodes.go, nodes_test.go, note_node.go, note_node_test.go, phonetic_variation_node.go, phonetic_variation_node_test.go, place_node.go, place_node_test.go, romanized_variation_node.go, romanized_variation_node_test.go, tag.go, type_node.go, type_node_test.go
- Added more functions to PlaceNode to complete the PLAC spec.
- Added several new nodes; FormatNode, LatitudeNode, LongitudeNode, MapNode, NoteNode, PhoneticVariationNode, RomanizedVariationNode, TypeNode.
- Added CastNodes which creates a slice of a more specific node type.
- Added Phonetic and Romanized variation type constants.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/132)
=> Complete spec for PlaceNode. Fixes #11

gedcom2html/count_badge.go, gedcom2html/family_statistics.go, gedcom2html/header.go, gedcom2html/individual_link.go, gedcom2html/individual_statistics.go, gedcom2html/octicon.go, gedcom2html/place_link.go, gedcom2html/place_statistics.go, gedcom2html/source_statistics.go, html/number.go
- Statistics page now show thousands separator on numbers.
- Fixed bug where Individuals link in the header may goto a page that does not exist.
- Added "location" icon for place names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/135)
=> Minor fixes for gedcom2html. Fixes #114

gedcom2html/event_statistics.go, gedcom2html/header.go, gedcom2html/main.go, gedcom2html/page.go, gedcom2html/place_link.go, gedcom2html/surname_in_list.go, gedcom2html/surname_link.go, gedcom2html/surname_list_page.go
- The Surnames page lists the surnames with an individual count.
- Fixed missing commas on some of the Statistics for events.
- Added options to optionally disable each of the pages.
- Fixed bug where an empty place would display the icon without the name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/137)
=> Adding Surnames page. Fixes #127

decoder.go, decoder_test.go, document.go, encoder.go
Streams that start with a Byte Order Mark are now understood correctly. The BOM is automatically restored to keep compatibility and consistency, but it can be disabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/140)
=> Fix Decoder with BOM. Fixes #139

.travis.yml, Makefile, README.md
This makes it much easier for people that don't have or want a Go environment to be able to use the gedcom tools.
This also adds support for Go 1.11.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/144)
=> Compile and upload releases. Fixes #141

decoder.go, decoder_test.go, document.go, document_test.go, gedcom2html/badge_pill_test.go, html/anchor_test.go, individual_node.go, individual_node_test.go, node.go
There was a bug that caused copied documents to avoid using the appropriate constructor that would have setup the MaxLivingAge. This utimately meant that indviduals were returning true under some cases for IsLiving.
There was also a related bug found where MaxLivingAge == 0 did not always perform the way the documentation outlined.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/156)
=> Fixed a bug with IsLiving

decoder.go, decoder_test.go, document.go, document_test.go, encoder.go, family_node_test.go, gedcom2json/transform.go, gedcom2json/transform_test.go, individual_node_test.go, individual_nodes_test.go, node.go, node_diff_test.go
Document.Nodes is no longer publically accessible and added a NewDocumentWithNodes() constructor.
Instead there are new methods Nodes() and AddNode() on the Document. These are required to make sure the proper cache mechanisms now and in the future can be triggered when the document changes.
It was stated before that you should never instantiate Document manually. However, all of the tests that did this have now been updated to use one of the constructors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/162)
=> Remove Document.Nodes

README.md, gedcomdiff/main.go
The functional change of this patch is to add the "-minimum-weighted-similarity" and "-minimum-similarity" to gedcomdiff. These map directly to the comparions options of the same name.
There is also come cleanup of documentation and CLI docs on the gedcomdiff tool.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/163)
=> gedcomdiff options for minimum similarity

gedcomdiff/diff_page.go, gedcomdiff/individual_compare.go, gedcomdiff/main.go, html/individual_name_and_dates.go, html/individual_name_and_dates_link.go, html/link.go
- Added "-sort-similarities" to sort the individuals by similarity (highest first) rather than by name.
- It now shows the similarity metric for indviduals that match.
- The individiual index now has links to the individuals below.
- Fixed a minor bug where individuals with missing dates would show "()".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/164)
=> Show gedcomdiff similarities

baptism_node.go, birth_node.go, burial_node.go, date_node.go, date_node_test.go, date_nodes.go, date_nodes_test.go, dater.go, dater_test.go, death_node.go, event_node.go, gedcom2html/place_event.go, number.go, number_test.go, residence_node.go, years.go
DateNodes is a slice of zero or more DateNodes.
Even though this slightly breaks compatibility because the name of the functions are different the functionality is exactly the same.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/167)
=> Adding DateNodes type

Gopkg.lock, Gopkg.toml, age.go, age_constraint.go, age_constraint_test.go, age_test.go, assert_test.go, date.go, date_node.go, date_nodes.go, date_nodes_test.go, date_test.go, dater.go, dater_test.go, decoder_test.go, individual_node.go, individual_node_test.go, number_test.go
This is a surprisingly large change. It introduces several new types and a lot of new functionality centered around the main new type, Age.
Age can be use used to describe a real or theoretical age of an individual at the time of their death or another event. The Age containts other attributes such as whether it is an estimation, handles date ranges and calculated metrics about whether they would be alive during the date range.
Most of the new functionality can be seen through IndividualNode.Age() and IndividualNode.AgeOf().
The other changes worth noting are:
- DateNode.IsValid returns true only when the node is not nil and the start and end date are non-zero.
- DateNode.IsExact and Date.IsExact will return true if the date range represents a single day with an exact constraint.
- Fixed …
=> Adding Age type and calculations. Fixes #9

.gitignore, Makefile, gedcomq/accessor.go, gedcomq/accessor_test.go, gedcomq/doc.go, gedcomq/engine.go, gedcomq/engine_test.go, gedcomq/expression.go, gedcomq/functions.go, gedcomq/length.go, gedcomq/length_test.go, gedcomq/main.go, gedcomq/parser.go, gedcomq/parser_test.go, gedcomq/question_mark.go, gedcomq/question_mark_test.go, gedcomq/util.go, gedcomq/util_test.go, simple_node.go
Package gedcomq is a command line tool and query language for GEDCOM files. It is heavily inspired by jq, in name and syntax. The basic syntax of the tool is:
gedcomq -gedcom file.ged '.Individuals | .Name'
The functions are automatically discovered through the gedom package.
This initial version is quite rudimentary and does not handle errors gracefully. However, it does demonstrate what the most basic queries look like.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/170)
=> Introducing gedcomq

q/accessor_expr.go, q/binary_expr.go, q/binary_expr_test.go, q/call_expr.go, q/call_expr_test.go, q/constant_expr.go, q/constant_expr_test.go, q/doc.go, q/engine_test.go, q/expression.go, q/first_expr.go, q/first_expr_test.go, q/formatter.go, q/formatter_test.go, q/functions.go, q/last_expr.go, q/last_expr_test.go, q/length_expr.go, q/object_expr.go, q/only_expr.go, q/only_expr_test.go, q/parser.go, q/parser_test.go, q/question_mark_expr.go, q/question_mark_expr_test.go, q/token.go, q/token_test.go, q/variable_expr.go
The gedcomq syntax has been greatly improved with:
- Adding binary operators; "=", "!=", ">", ">=", "<" and "<=". These work for number and strings. All strings are treated as non case sensitve and automatically trim surrounding whitespace.
- Added a new function "Only". It can be used to filter slices based on an expression. This also means that functions can take a real evaluated argument instead of only a constant.
- Added number (1.23) and string constants ("foo") to the syntax.
Other improvements:
- Added a trailing newline for JSON and pretty JSON outputs so they are more friendly to the CLI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/179)
=> Added binary operators to gedcomq

gedcomq/main.go, node_set_test.go, q/combine_expr.go, q/combine_expr_test.go, q/doc.go, q/engine.go, q/engine_test.go, q/functions.go, q/parser.go, q/parser_test.go, q/question_mark_expr_test.go, q/value_expr.go, util/cli.go
Multiple documents can be provided by supplying "-gedcom" several times. New variables Document1, Document2, etc can be used to access these files.
Also added a Combine() function which creates a single slice out of multiple slices of the same type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/185)
=> gedcomq now supports multiple documents

Gopkg.lock, Gopkg.toml, copy_test.go, document.go, flatten.go, flatten_test.go, gedcomdiff/diff_page.go, gedcomdiff/individual_compare.go, gedcomdiff/main.go, gedcomtune/main.go, individual_node.go, individual_node_test.go, individual_nodes.go, individual_nodes_test.go, merge.go, merge_test.go, node.go, node_set.go, nodes.go, q/question_mark_expr_test.go, simple_node.go, simple_node_test.go, surrounding_similarity.go, surrounding_similarity_test.go
- IndividualNodes.Merge() uses the expensive but more accurate Compare algorithm to determine the best way to merge two slices of individuals.
- Flatten() returns a slice of nodes from a tree structure.
- Node.SetNodes() can be used to replace or remove all child nodes.
- Fixed a bug where MergeNodes() may not correctly childen from two equal nodes.
- MergeDocumentsAndIndividuals() merges two documents while also merging similar individuals.
- github.com/google/go-cmp has been added to make comparing more complex structures easier through assertEquals().
- SurroundingSimilarity now includes the SimilarityOptions as a propety. This makes the interface more friendly and String more appropriate.
- Fixed a bug in MergeNodeSlices() where the right slice may get mangled.
- Added …
=> Heavily improved merging and much more

gedcomdiff/diff_page.go, gedcomdiff/diff_page_test.go, gedcomdiff/main.go
The changes in v31.0.0 left a bug where the similarity may be nil and so gedcomdiff would panic when generating the HTML.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/189)
=> Fixed a bug where gedcomdiff would panic

individual_node.go, individual_node_test.go, merge_test.go
Individual surrounding similarity comparisons are very expensive, so comparing two large trees takes a huge amount of CPU time.
The speed has been increased by an order of magnitude (5-10x faster) by taking advantage of excluding unessesary comparisons.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/190)
=> Much faster individual comparisons. Fixes #186

gedcomdiff/main.go
This fixes a bug that lead to "-sort" being required. It is now correctly optional with a default value of "written-name" as originally documented.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/198)
=> gedcomdiff: Fix required "-sort". Fixes #196

README.md
The original room gedcom-go has been removed and a new one, "gedcom-app" has been created. It was renamed because that room will also be used for gedcom-app repository and https://gedcom.app.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/201)
=> Update gitter room

event_node.go, event_node_test.go
Events are now considered equal if both do not have any dates, but all other attributes are the same.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/206)
=> events: new equality edge case

individual_nodes.go, similarity_options_test.go
DefaultMinimumSimilarity has been changed to 0.733 (and all metrics that depend on this) because there seems to be a sweet spot around 0.733333 when comparing large trees that it should remain just under.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/208)
=> compare: change DefaultMinimumSimilarity

date_node.go, gedcomdiff/main.go, individual_nodes.go, progress.go
CompareProgress has been renamed to Progress and has a a new property for Add, but still remains backwards compatible.
This was done becuase it will be used for other progress notifications, and needs to be more generic and flexible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/209)
=> compare: CompareProgress -> Progress

Gopkg.lock, Gopkg.toml, gedcomdiff/main.go
We were using github.com/cheggaaa/pb v2 which is actually still in progress (excuse the pun) and not yet as feature rich as the current stable v1. Reverting back added a few more features to the progress bar.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/210)
=> gedcomdiff: better progress bar

README.md, gedcomdiff/main.go, html/card.go, html/diff_page.go, html/diff_page_test.go, html/diff_row.go, html/event_statistics.go, html/family_statistics.go, html/individual_additional_names.go, html/individual_compare.go, html/individual_events.go, html/individual_name_and_sex.go, html/individual_statistics.go, html/place_statistics.go, html/source_statistics.go, individual_nodes.go, individual_nodes_test.go, merge_test.go, similarity_options.go, similarity_options_test.go, util/filter_flags.go
Controls if two individuals should be considered a match by their pointer value.
The default value is 0.735 which means that the individuals will be considered a match if they share the same pointer and hit the same default minimum similarity.
A value of 1.0 would have to be a perfect match to be considered equal on their pointer, this is the same as disabling the feature.
A value of 0.0 would mean that it always trusts the pointer match, even if the individuals are nothing alike.
This option makes sense when you are comparing documents that have come from the same base and retained the pointers between individuals of the existing data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> gedcomdiff: Added -prefer-pointer-above

decoder.go, decoder_test.go, familysearch_id_node.go, familysearch_id_node_test.go, individual_node.go, individual_node_test.go, q/functions.go, q/merge_documents_and_individuals_expr.go, q/merge_documents_and_individuals_expr_test.go, tag.go, tag_test.go, unique_id_node_test.go, uuid.go, uuid_test.go
FamilySearchIDNode is the unique identifier for the person on FamilySearch.org. A FamilySearch ID always takes the form of: LZDP-V9V
There are several known tags that carry the FamilySearch ID:
- _FID (UnofficialTagFamilySearchID1): Seen exported from MacFamilyFree.
- _FSFTID (UnofficialTagFamilySearchID2): Some other applications.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/219)
=> FamilySearchIDNode

filter.go, filter_test.go, util/filter_flags.go
When enabled death tags (DEAT) will be removed if they have no children. This is because some applications use the death tag as a marker without any further information.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/224)
=> gedcomdiff: Added "-no-empty-deaths" option

date.go, date_node_test.go
"Circa" representing "Abt." is also often used as "ca", "ca.", "cca" and "cca."
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/228)
=> DateNode: More variations for "circa". Fixes #222

decoder.go, decoder_test.go
Pointers can really include anything, apart from a "@". This patch also adds some more test edge cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/231)
=> Decoder: More flexible pointers. Fixes #230

date.go, date_node.go, date_node_test.go, date_range.go, date_range_comparison.go, date_range_comparison_test.go, date_range_test.go, date_test.go
Most of the date range functionality was in the DateNode which means it could not be used in other places we need to represent date ranges. There is now a DateRange type where most of these methods have been moved to.
Also, more comprehensive comparisons can be made like Before, After and range comparison constants.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/234)
=> Refactoring DateNode to DateRange

date_node.go, document.go, document_test.go, duration.go, duration_test.go, errors.go, q/question_mark_expr_test.go, unparsable_date_warning.go, warner.go, warning.go, warnings.go
This is the first of its kind. Nodes can now implement a Warner interface which returns a slice of Warning entities. Document also implements Warner to aggregate all warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/237)
=> Warning: Unparsable date

decoder.go, decoder_test.go
I'm not sure if this is strickly permitted in the GEDCOM standard and the extra space will not be retained when encoded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/244)
=> Decoder: Allow double space before tag. Fixes #243

decoder.go, decoder_test.go
It is not valid for GEDCOM values to contain new lines or carriage returns. However, some application dump data without correctly using the CONT tags.
Strictly speaking we should bail out with an error but there are too many cases that are difficult to clean up for consumers so we offer and option to permit it.
When enabled any line than cannot be parsed will be considered an extension of the previous line (including the new line character).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/245)
=> Decoder: Allow mulitline GEDCOM values

husband_node.go, wife_node.go
Fixed a bug where locating a WifeNode through the individual pointer may not work becuase of a nil cast. Interesting this bug did not apply to the HusbandNode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/247)
=> WifeNode: pointer may be invalid

individual_nodes.go, individual_nodes_compare_options.go, nodes.go
The progress calculation was easily mangled leading to weird results like negative totals. All of the comparison state has been moved into the IndividualNodesCompareOptions to remedy this.
This also fixes a minor bug with a race condition in the NodesWithTag() caching.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/248)
=> Compare: Fix progress calculation

child_born_before_parent_warning.go, document.go, document_test.go, family_node_test.go, siblings_born_too_close_warning.go, unparsable_date_warning.go, warning.go, warning_context.go
A WarningContext describes the entity the warning is attached to.
For example if the warning was an unparsable date for the birth of an individual then the Individual would be set, but not the Family.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/249)
=> Added WarningContext

.gitignore, child_born_before_parent_warning.go, gedcomq/main.go, individual_node.go, q_marshal.go, q_marshal_test.go, siblings_born_too_close_warning.go, unparsable_date_warning.go, warning.go, warnings.go
QMarshaller provides MarshalQ which works in a similar way to the JSON marshaller. It is used to provide custom formatting for the q engine.
If objects do not implement this interface then the behavior remains the same.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/250)
=> Added QMarshaller interface

child_born_before_parent_warning.go, date_range.go, document_test.go, incorrect_event_order_warning.go, individual_node.go, individual_nodes_test.go, siblings_born_too_close_warning.go, simple_warning.go, unparsable_date_warning.go
IncorrectEventOrderWarning produces warnings where events for an individual are in an incorrect order. For example a burial before a death event, or a baptism before a birth.
This patch also creates a SimpleWarning so there is less duplicate code between warnings and a few helper methods for events on IndividualNode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/252)
=> Added IncorrectEventOrderWarning

document.go, family_node.go, family_node_test.go, individual_node.go, married_too_old_warning.go
MarriedTooOld is raised when a spouse was married at an age greater than 100 (DefaultMaxMarriageAge).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/255)
=> Added MarriedTooOldWarning

q/accessor_expr.go, q/accessor_expr_test.go, q/question_mark_expr_test.go
If an accessor fails the panic message and stack trace are now added to the error returned.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/259)
=> q: Attach stack trace on panic

child_node.go, child_node_test.go
FIxed a bug where the Individual() of a ChildNode may panic if the individual cannot be resolved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/260)
=> ChildNode: Individual() may panic

q/html_formatter.go
Fixed a bug where HTMLFormatter was writing to os.Stdout instead of the Writer buffer as it should.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/261)
=> HTMLFormatter: Remove os.Stdout

child_node_test.go, decoder.go, decoder_test.go, q/accessor_expr_test.go
Since AllowMultiLine will allow blank lines to continue there is a bug where this might lead to node values having a traing new line.
For these cases the error cascades down to node that need to decode the value (such as a date) and the added newline break the regexps.
Now new lines can still exist in multiline values, but the value itself cannot end with a new line. This is a good balance been compatibility and consistence.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/262)
=> Decoder: AllowMultiLine mangles some nodes

html/core/components.go
A nasty little bug where the nil check on a set of components was not correctly identifying a nil Component.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/265)
=> HTML: Fix panic on nil Component

gedcom2html/main.go, html/core/directory_file_writer.go, html/core/file.go, html/core/file_writer.go, html/family_list_page.go, html/individual_list_page.go, html/individual_page.go, html/individuals.go, html/place_list_page.go, html/place_page.go, html/publish.go, html/publish_header.go, html/publish_test.go, html/source_list_page.go, html/source_page.go, html/statistics_page.go, html/surname_list_page.go
The code to publish a website has now been moved into the html package as Publisher. This means that the gedcom2html is much lighter.
The Publisher can now be customised to write to the file system, or any other storage mechanism and it can now render the website in parallel making it much faster. This can be configured with the new "-jobs" option.
The "-checksum" option has been removed from the gedcom2html because it was already problematic at best and not needed now that the rendering process is much faster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/266)
=> gedcom2html: Faster and customizable rendering

decoder.go, decoder_test.go, gedcomdiff/main.go
AllowInvalidIndents allows a child node to have an indent greater than +1 of the parent. AllowInvalidIndents is disabled by default because if this happens the GEDCOM file is broken in some possibly serious way and certainly not a valid GEDCOM file.
The biggest problem with having the indents wrongly aligned is that nodes that are expected to be a certain depth (such as NPFX inside a NAME) will probably break or interfere with a traversal algorithm that is not expecting the node to be there/at that level.
Another important thing to note is that the incorrect indent level will not be retained when writing the Document back to a GEDCOM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> decoder: Added AllowInvalidIndents

residence_node.go, residence_node_test.go
This bug was caught when differences showed up after comparing the same file to itself.
Residences are equal if they contain the same place but both do not specify a date. Previously it was only if they share the same date.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/285)
=> ResidenceNode: Equality without dates

README.md
gedcom.app is no longer maintained and has been now taken down.
=> Docs: Remove gedcom.app links

.travis.yml, Makefile
Windows 32bit support has been removed. The names of releases are also more understandable for non-technical people. Simply "linux", "macos" and "windows".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/290)
=> CI: Remove windows 32bit releases 

html/individual_index_header.go, html/publish_test.go, individual_node.go
Two bugs fixed:
1. One bug was caused by taking the first letter of the name, which may not be the first letter of the surname. So these individuals were not appearing on the index.
2. Children with an unknown spouse were not being displayed becuase it was incorrectly comparing the family pointer instead of the individual pointer.
Fixes #276
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/293)
=> Publish: Fix surname index and missing children

html/individual_additional_names.go
Names would not show as additional names if they were "Normal" names (ie. not married name, etc). Now it shows all names excluding the first name.
Fixes #275
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/294)
=> Publish: Fix missing additional names

filter.go, filter_flags.go, filter_flags_test.go, filter_test.go
Also provides RemoveDuplicateNamesFilter filter function, and fixes a bug with returning children from a filter function being mistakenly truncated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/299)
=> Added "-no-duplicate-names"

q/doc.go, q/functions.go, q/nodes_with_tag_path.go, q/nodes_with_tag_path_test.go, q/question_mark_expr_test.go
NodesWithTagPath returns all of the nodes that have an exact tag path.
The number of nodes returned can be zero and tag must match the tag path
completely and exactly.
Find all Death nodes that belong to all individuals:
.Individuals | NodesWithTagPath("DEAT")
From the individuals find all the Date nodes within only the Birth nodes.
.Individuals | NodesWithTagPath("BIRT", "DATE")
Combine all of the birth and death dates:
Births are .Individuals | NodesWithTagPath("BIRT", "DATE") | {type: "birth", date: .String};
Deaths are .Individuals | NodesWithTagPath("DEAT", "DATE") | {type: "death", date: .String};
Combine(Births, Deaths)
Fixes #300
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Adding NodesWithTagPath() to q

cmd/gedcom/main.go, cmd/gedcom/warnings.go
Since the refactoring into a single CLI tool the warnings were kind of
forgotten about. It is possible to get the warnings through query, but
that's difficult and problematic. This makes the warnings command a
first class citizen:
gedcom warnings myfile.ged
https://github.com/elliotchance/gedcom/wiki/Warnings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/304)
=> Adding "gedcom warnings"

copy.go, copy_test.go, document.go, filter.go, filter_flags.go, filter_flags_test.go, filter_test.go, flatten.go, flatten_test.go, html/individual_compare.go, individual_nodes.go, individual_nodes_test.go, merge.go, merge_test.go, nodes.go
A bug was found in DeepCopy (or really anything that ends up copying a
node) that some nodes (such as the husband, wife or child) cannot be
created without a FamilyNode. The bug was that the FamilyNode was not
being tracked at a high enough level so duplicated nodes would not
inherit it correctly. Even though there was already code to do that, it
wasn't working correctly.
This lead to a greater look at how the APIs work and I realised that the
document must be provided in many cases because any process that
directly or indirectly needs to copy a node will need this proper
context.
Even though this patch breaks several of the existing APIs (by adding a
document parameter) none of the behaviour has changed. If you are
unsure when updating the library you should create a new document and …
=> Document context for copying nodes

child_node.go, family_node.go, family_node_test.go, nodes.go, simple_node.go
These changes should add a FAMS record to the individual when they are added as a spouse to a family node.   See https://github.com/elliotchance/gedcom/issues/309   I hope I handled the cache values appropriately, originally that was confusing me as to why my delete tests were failing, although GEDCOMString() was showing what I expected.
I'll tackle children (FAMC) codes separately, soon.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/310)
=> Add FAMS code in individual nodes when made a spouse in a family.

family_node.go, family_node_test.go
So I thought I had run all of the tests, but I obviously hadn't as the test for child_node is now failing -- with the actual failure being the doc.AddFamilyWithHusbandAndWife("F1", p1, nil) call.  
This fixes that problem, by quietly returning if you try to SetWife() or SetHusband() with nil and it's already nil.   While I was there I fixed some formatting, and used IsNil() for my tests.
Also added some explicit tests for AddFamilyWithHusbandAndWife() in the familyTests.
So really, really sorry about this -- I tripled checked that the tests were all OK this time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/311)
=> If spouse is already nil, short-circuit out.
