elliotchance/gedcom

date.go
date_constraint.go
date_constraint_test.go
date_node.go
date_node_test.go
date_test.go
util.go
util_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/7)

Much richer support for DATE node and date values. Fixes #4

---

gedcom2html/header.go
gedcom2html/individual_index_header.go
gedcom2html/individual_index_letter.go
gedcom2html/individual_list_page.go
gedcom2html/main.go
gedcom2html/page.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/15)

Split individuals into letters for gedcom2html

---

date.go
date_node.go
date_node_test.go
date_test.go
years.go
years_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/16)

Date compare

---

jaro.go
jaro_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/17)

String compare

---

.travis.yml

Fixes #23
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/26)

Adding code coverage. Fixes #23

---

gedcom2json/main.go
gedcom2json/transform.go
gedcom2json/transform_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/19)

Move Transform() to gedcom2json. Fixes #8

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/28)

Adding codecov badge. Fixes #27

---

util.go
util_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/29)

Added First() and Last(). Fixes #18

---

README.md
family_node.go
gedcom2html/event_statistics.go
gedcom2html/family_in_list.go
gedcom2html/family_statistics.go
gedcom2html/individual_events.go
gedcom2html/place_event.go
gedcom2html/util.go
gedcom2json/main.go
gedcom2json/transform.go
gedcom2json/transform_test.go
gedcom2text/main.go
gedcom2text/name.go
individual_node.go
name_node.go
node.go
nodes.go
nodes_test.go
simple_node.go
source_node.go
util.go
util_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/34)

Refactor Node functions outside of Node interface. Fixes #32

---

individual_node.go
individual_node_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/39)

Adding Births(), Baptisms(), Death() and Burials() for individuals. Fixes #30

---

date_node.go
individual_node.go
individual_node_test.go
nodes.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/44)

Added EstimatedBirthDate() and EstimatedDeathDate(). Fixes #37

---

date_node.go
date_node_test.go
individual_node.go
individual_node_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/46)

 Added Similarity() for IndividualNode. Fixes #42

---

descent.go
document.go
document_test.go
family_node.go
gedcom2html/individual_list_page.go
individual_node.go
individual_node_test.go
individual_nodes.go
individual_nodes_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/47)

Added Similarity() for new type IndividualNodes. Fixes #45

---

family_node.go
family_node_test.go
individual_node.go
individual_node_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/55)

Added Similarity() for FamilyNode. Fixes #51.

---

individual_node.go
individual_node_test.go
surrounding_similarity.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/58)

Added SurroundingSimilarity() and type of the same name. Fixes #49

---

.travis.yml
Gopkg.lock
surrounding_similarity.go
surrounding_similarity_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/59)

Added WeightedSimilarity(). Fixes #57

---

date.go
date_node.go
date_node_test.go
date_test.go
node.go
node_diff_test.go

- Equals() has been implemented for Date and DateNode.
- Added Date.IsZero() for nil-like checking of dates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/79)

Implementing Equals(). Fixes #78

---

README.md
node.go
node_test.go

DeepEqual tests if left and right are recursively equal.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/87)

Adding DeepEqual(). Fixes #85

---

date_node.go
date_node_test.go

- Added MinimumDateNode() and MaximumDateNode()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/92)

Added functions for min and max date. Fixes #43

---

event_node.go
event_node_test.go
residence_node.go
tag.go

- Added EventNode with Dates and implements Yearer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/94)

Added EventNode. Fixes #89

---

decoder.go
decoder_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/96)

Fix bug with EventNode in NewNode. #89

---

gedcom2html/family_list_page.go
gedcom2html/individual_list_page.go
gedcom2html/individual_page.go
gedcom2html/main.go
gedcom2html/place_list_page.go
gedcom2html/place_page.go
gedcom2html/source_list_page.go
gedcom2html/source_page.go
gedcom2html/statistics_page.go
gedcomdiff/diff_page.go
gedcomdiff/main.go
html/google_analytics.go
html/page.go

Added "-google-analytics-id" option to gedcom2html. If provided it will ad the appropriate GA header to all pages produced.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/115)

Adding Google Analytics. Fixes #113

---

birth_node.go
birth_node_test.go
date_node.go
date_node_test.go
event_node.go
event_node_test.go
family_node.go
family_node_test.go
individual_node.go
individual_node_test.go
name_node.go
name_node_test.go
name_type.go
nodes.go
nodes_test.go
residence_node.go
residence_node_test.go
simple_node.go
simple_node_test.go
source_node.go
source_node_test.go
util.go
util_test.go

- Almost all of the functions on specific node type will return nil-like values when the instance is also nil.
- Added Pointer() which works in the same way as Value().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/119)

Allow node function to handle nil gracefuly. Fixes #117

---

Gopkg.lock
Gopkg.toml
README.md
name_node.go
name_node_test.go

Format works similar to fmt.Printf where placeholders represent different components of the name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/123)

Adding NameNode.Format. Fixes #1

---

gedcom2html/nav_pills_row.go
gedcom2html/place_list_page.go
gedcom2html/place_page.go
gedcom2html/places.go
gedcom2html/surname_index.go
util/slice.go
util/slice_test.go

- The Places page now has a country index at the top.
- Added util.StringSliceContains().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/134)

Countries are not headers on Places page. Fixes #129

---

gedcom2html/place_event.go

Before this fix each of the individual Place pages would show an empty table.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/145)

Place page now shows events. Fixes #142

---

README.md
gedcom2html/header.go
gedcom2html/main.go

The "-checksum" option for gedcom2html makes it easier to sync large outputs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/146)

Added "-checksum" option. Fixes #136

---

.gitignore
.travis.yml
Makefile
gedcom2html/badge_pill_test.go
gedcom2text/main_test.go
gedcomdiff/main_test.go
gedcomtune/main_test.go
html/anchor_test.go

Added new targets to the Makefile so the Travis configuration is now more simple
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/154)

Code coverage over all packages. Fixes #138

---

document.go
individual_node.go
individual_node_test.go

This makes it more relaible to determine IsLiving for an individual.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/155)

Adding MaxLivingAge. Fixes #31

---

number.go
number_test.go

Number can be used to transform a number into another representation such as roman numerals.
It is not used anywhere in the library yet, but it will be when we start to introduce relationships.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/166)

Add Number type

---

q/accessor_expr.go
q/accessor_expr_test.go
q/doc.go
q/engine_test.go
q/first_expr_test.go
q/last_expr.go
q/last_expr_test.go
q/object_expr.go
q/object_expr_test.go
q/parser.go
q/parser_test.go
q/statement.go
q/token.go
q/token_test.go
q/variable_expr.go

Objects creates an object from keys and values, like:
.Individuals | { name: .Name, age: .Age }
Also fixed a bug where using an accessor on a nil value would cause a panic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/177)

Added object syntax to gedcomq

---

gedcomdiff/main.go
gedcomq/main.go
object_mapper.go
q/doc.go
q/formatter.go
q/formatter_test.go
simple_node.go
util/cli.go

The "-format" option allows gedcomq to output in two new formats; "pretty-json" and "csv".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/178)

Added "-format" for gedcomq

---

merge.go
node_set.go
node_set_test.go

NodeSet is a collection of unique nodes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/182)

Added NodeSet

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/187)

Adding CodeClimate

---

gedcomdiff/main.go
html/age_test.go
html/anchor_test.go
html/diff_page.go
html/diff_page_test.go
html/diff_row.go
html/footer_row_test.go
html/individual_compare.go
html/text.go
html/text_test.go

This is so gedcomdiff functionality can be used outside of the binary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/195)

Moved gedcomdiff HTML elements to html package

---

.travis.yml
Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/197)

Adding ".exe" to windows binaries. Fixes #193

---

gedcom2html/main.go
gedcom2json/main.go
gedcom2text/main.go
gedcomdiff/main.go
gedcomq/main.go
gedcomtune/main.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/199)

Check required flags in CLI. Fixes #194

---

date_node.go
date_node_test.go

A phrase is any statement offered as a date when the year is not recognizable to a date parser, but which gives information about when an event occurred. The date phrase is enclosed in matching parentheses.
Phrases can only be compared to themselves and they must be the exact same value to be considered equal.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/205)

dates: added phrases

---

q/doc.go
q/functions.go
q/merge_documents_and_individuals_expr.go
q/merge_documents_and_individuals_expr_test.go
q/question_mark_expr_test.go

MergeDocumentsAndIndividuals(doc1, doc2) merges two documents while also merging similar individuals.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/191)

Add MergeDocumentsAndIndividuals to gedcomq

---

tag.go
tag_test.go
unique_id_node.go
unique_id_node_test.go
uuid.go
uuid_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/218)

_UID: Unofficial unique ID

---

html/diff_row.go
individual_node.go
individual_nodes.go
individual_nodes_test.go
merge_test.go
simple_node_test.go
string_set.go
string_set_test.go
unique_id_node_test.go

An individual can have more than one unique identifier that can be used in comparison and merging processes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/225)

gedcomdiff: unique identifiers

---

date.go
date_node_test.go
date_range.go
date_range_test.go
date_test.go
individual_nodes_test.go
years_test.go

When parsing a date based on a string the error will be placed in ParseError.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/235)

Date: add ParseError

---

date_node.go
duration.go
duration_test.go
errors.go

A new Duration type with whole-day resolution and pretty formatting is ideal when dealing with durations from subtracting dates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/236)

Date: Subtract dates into a Duration

---

child_born_before_parent_warning.go
child_node.go
date_node.go
document_test.go
family_node.go
family_node_test.go
individual_node.go

When the child is born before either parent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/238)

Warning: ChildBornBeforeParent

---

family_node.go
family_node_test.go
husband_node.go
individual_node_pair.go
individual_node_pairs.go
siblings_born_too_close_warning.go
tag.go
wife_node.go

If siblings were born less than 9 months apart.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/239)

Warning: SiblingsBornTooClose

---

date_node_test.go
document_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/240)

Warning: Add tests for UnparsableDate

---

gedcomdiff/main.go

This enables AllowMultiLine on the Decoder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/246)

gedcomdiff: Added -allow-multi-line

---

family_node.go
family_node_test.go
inverse_spouses_warning.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/258)

Added InverseSpousesWarning

---

individual_node.go
individual_node_test.go
multiple_sexes_warning.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/257)

Added MultipleSexesWarning

---

.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/263)

Go: Add v1.12 to CI

---

.gitignore
date_range.go
family_node.go
family_node_test.go
individual_node.go
individual_node_test.go

This fixes various edge cases for a variety of warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/264)

Warnings: Fix some edge cases

---

document.go
html/individual_index_header.go
html/individual_list_page.go
html/individuals.go
html/publish.go
html/publish_header.go
html/publish_test.go
html/util.go

Index letters (on the Individuals) page will now not show up if there are no living individuals for that index letter.
This also fixes a bug where the sources were not being published.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/267)

Publish: Better handling of index letters

---

document.go
html/family_list_page.go
html/individual_index_header.go
html/individual_list_page.go
html/individual_page.go
html/individuals.go
html/place_list_page.go
html/place_page.go
html/publish.go
html/publish_header.go
html/source_list_page.go
html/source_page.go
html/statistics_page.go
html/surname_list_page.go
html/util.go

Fixes to ensure we do not need to syncronise maps when rendering in parallel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/268)

Publish: Fixes for concurrency

---

.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/286)

CI: Adding Go v1.13

---

Makefile
cmd/gedcom/main.go
cmd/gedcom/version.go

Fixes #296
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/elliotchance/gedcom/298)

CLI: Added "version" command
